plugins {
  id 'org.jetbrains.kotlin.multiplatform'
  id 'com.android.kotlin.multiplatform.library'
}

kotlin {
  androidLibrary {
    namespace = "com.android.example.module_e9f52de3"
    compileSdk = 31
    minSdk = 24

      withAndroidTestOnDeviceBuilder {
        it.compilationName = "instrumentedTest"
        it.defaultSourceSetName = "androidInstrumentedTest"
        it.sourceSetTreeName = "test"
      }

      withAndroidTestOnJvmBuilder {
        it.defaultSourceSetName = "androidUnitTest"
      }

      sourceSets {
        androidMain {
          dependencies {
      annotationProcessor("com.google.dagger:dagger-compiler:2.43.1")
      api(project(":module07:module194:module1"))
      api(project(":module07:module506:module1"))
      api(project(":module07:module504:module01"))
      api(project(":module07:module504:module10"))
      api(project(":module07:module562:module10"))
      api("com.google.dagger:dagger:2.43.1")
      api("com.squareup.retrofit2:retrofit-mock:2.8.1")
      api("com.squareup.retrofit2:retrofit:2.8.1")
      api("io.reactivex.rxjava2:rxjava:2.2.21")
      compileOnly("androidx.annotation:annotation:1.0.0")
      implementation(project(":module07:module194:module1"))
      implementation(project(":module07:module274:module2"))
      implementation(project(":module07:module488:module1"))
        }
      }
      androidInstrumentedTest {
        dependencies {
      implementation("androidx.annotation:annotation:1.0.0")
        }
      }
      androidUnitTest {
        dependencies {
        }
      }
    }
  }
}
