plugins {
  id 'org.jetbrains.kotlin.multiplatform'
  id 'com.android.kotlin.multiplatform.library'
}

kotlin {
  androidLibrary {
    namespace = "com.android.example.module_577831c7"
    compileSdk = 31
    minSdk = 24

      withAndroidTestOnDeviceBuilder {
        it.compilationName = "instrumentedTest"
        it.defaultSourceSetName = "androidInstrumentedTest"
        it.sourceSetTreeName = "test"
      }

      withAndroidTestOnJvmBuilder {
        it.defaultSourceSetName = "androidUnitTest"
      }

      sourceSets {
        androidMain {
          dependencies {
      api(project(":module07:module343:module5"))
      api("javax.inject:javax.inject:1")
      compileOnly("androidx.annotation:annotation:1.0.0")
        }
      }
      androidInstrumentedTest {
        dependencies {
      implementation("androidx.annotation:annotation:1.0.0")
        }
      }
      androidUnitTest {
        dependencies {
        }
      }
    }
  }
}
