plugins {
  id 'org.jetbrains.kotlin.multiplatform'
  id 'com.android.kotlin.multiplatform.library'
}

kotlin {
  androidLibrary {
    namespace = "com.android.example.module_056d57d8"
    compileSdk = 31
    minSdk = 24

      withAndroidTestOnDeviceBuilder {
        it.compilationName = "instrumentedTest"
        it.defaultSourceSetName = "androidInstrumentedTest"
        it.sourceSetTreeName = "test"
      }

      withAndroidTestOnJvmBuilder {
        it.defaultSourceSetName = "androidUnitTest"
      }

      sourceSets {
        androidMain {
          dependencies {
      api("com.squareup.leakcanary:leakcanary-object-watcher-android-core:2.9.1")
      api("com.squareup.leakcanary:shark-android:2.9.1")
      compileOnly("androidx.annotation:annotation:1.0.0")
      implementation(project(":module07:module204:module4"))
      implementation(project(":module07:module358:module1"))
      implementation("com.squareup.curtains:curtains:1.2.4")
      implementation("com.squareup.leakcanary:plumber-android-core:2.9.1")
      implementation("org.jetbrains.kotlin:kotlin-bom:1.7.20")
        }
      }
      androidInstrumentedTest {
        dependencies {
      implementation("androidx.annotation:annotation:1.0.0")
        }
      }
      androidUnitTest {
        dependencies {
        }
      }
    }
  }
}
