plugins {
  id 'org.jetbrains.kotlin.multiplatform'
  id 'com.android.kotlin.multiplatform.library'
}

kotlin {
  androidLibrary {
    namespace = "com.android.example.module_a9e8b346"
    compileSdk = 31
    minSdk = 24

      withAndroidTestOnDeviceBuilder {
        it.compilationName = "instrumentedTest"
        it.defaultSourceSetName = "androidInstrumentedTest"
        it.sourceSetTreeName = "test"
      }

      withAndroidTestOnJvmBuilder {
        it.defaultSourceSetName = "androidUnitTest"
      }

      sourceSets {
        androidMain {
          dependencies {
      api(project(":module07:module109:module3:module2"))
      api(project(":module07:module194:module1"))
      api(project(":module07:module504:module01"))
      api(project(":module07:module504:module10"))
      api(project(":module16:module023:module1"))
      api(project(":module16:module031:module1"))
      api("com.google.dagger:dagger:2.43.1")
      api("javax.inject:javax.inject:1")
      compileOnly("androidx.annotation:annotation:1.0.0")
      implementation(project(":module07:module505:module1"))
      implementation(project(":module16:module036:module1"))
      implementation("com.squareup.okio:okio:3.0.0")
      implementation("org.jetbrains.kotlin:kotlin-bom:1.7.20")
        }
      }
      androidInstrumentedTest {
        dependencies {
      implementation("androidx.annotation:annotation:1.0.0")
        }
      }
      androidUnitTest {
        dependencies {
        }
      }
    }
  }
}
