plugins {
  id 'org.jetbrains.kotlin.multiplatform'
  id 'com.android.kotlin.multiplatform.library'
}

kotlin {
  androidLibrary {
    namespace = "com.android.example.module_088a7254"
    compileSdk = 31
    minSdk = 24

      withAndroidTestOnDeviceBuilder {
        it.compilationName = "instrumentedTest"
        it.defaultSourceSetName = "androidInstrumentedTest"
        it.sourceSetTreeName = "test"
      }

      withAndroidTestOnJvmBuilder {
        it.defaultSourceSetName = "androidUnitTest"
      }

      sourceSets {
        androidMain {
          dependencies {
      api(project(":module06:module05:module25:module5"))
      api(project(":module07:module584:module1"))
      compileOnly("androidx.annotation:annotation:1.0.0")
      implementation(project(":module06:module04:module1"))
      implementation(project(":module06:module05:module25:module1"))
      implementation(project(":module07:module143"))
      implementation(project(":module07:module146:module1"))
      implementation(project(":module07:module581:module3"))
      implementation(project(":module07:module583:module1"))
      implementation("androidx.test.espresso:espresso-core:3.3.0")
      implementation("org.jetbrains.kotlin:kotlin-bom:1.7.20")
        }
      }
      androidInstrumentedTest {
        dependencies {
      implementation("androidx.annotation:annotation:1.0.0")
        }
      }
      androidUnitTest {
        dependencies {
        }
      }
    }
  }
}
