plugins {
  id 'org.jetbrains.kotlin.multiplatform'
  id 'com.android.kotlin.multiplatform.library'
}

kotlin {
  androidLibrary {
    namespace = "com.android.example.module_cf9950e3"
    compileSdk = 31
    minSdk = 24

      withAndroidTestOnDeviceBuilder {
        it.compilationName = "instrumentedTest"
        it.defaultSourceSetName = "androidInstrumentedTest"
        it.sourceSetTreeName = "test"
      }

      withAndroidTestOnJvmBuilder {
        it.defaultSourceSetName = "androidUnitTest"
      }

      sourceSets {
        androidMain {
          dependencies {
      api(project(":module01:module06:module1"))
      api(project(":module07:module010:module2"))
      api(project(":module07:module318:module4"))
      api(project(":module07:module572"))
      compileOnly("androidx.annotation:annotation:1.0.0")
      implementation(project(":module07:module112"))
      implementation(project(":module07:module115"))
      implementation(project(":module07:module215"))
      implementation(project(":module07:module481:module5"))
      implementation("com.jakewharton.rxrelay2:rxrelay:2.1.0")
      implementation("io.reactivex.rxjava2:rxjava:2.2.21")
        }
      }
      androidInstrumentedTest {
        dependencies {
      implementation("androidx.annotation:annotation:1.0.0")
        }
      }
      androidUnitTest {
        dependencies {
      implementation(project(":module07:module166:module9"))
      implementation(project(":module07:module169:module3"))
      implementation(project(":module07:module354:module1"))
      implementation(project(":module07:module592:module4"))
      implementation("com.google.truth:truth:1.1.3")
      implementation("junit:junit:4.13.2")
      implementation("org.mockito:mockito-core:3.12.4")
        }
      }
    }
  }
}
