plugins {
  id 'org.jetbrains.kotlin.multiplatform'
  id 'com.android.kotlin.multiplatform.library'
}

kotlin {
  androidLibrary {
    namespace = "com.android.example.module_b5df69a1"
    compileSdk = 31
    minSdk = 24

      withAndroidTestOnDeviceBuilder {
        it.compilationName = "instrumentedTest"
        it.defaultSourceSetName = "androidInstrumentedTest"
        it.sourceSetTreeName = "test"
      }

      withAndroidTestOnJvmBuilder {
        it.defaultSourceSetName = "androidUnitTest"
      }

      sourceSets {
        androidMain {
          dependencies {
      annotationProcessor("com.google.dagger:dagger-compiler:2.43.1")
      api(project(":module06:module02:module1"))
      api(project(":module06:module02:module4"))
      api(project(":module06:module05:module28:module5"))
      api(project(":module06:module16:module05"))
      api(project(":module07:module004:module3"))
      api("com.google.dagger:dagger:2.43.1")
      compileOnly("androidx.annotation:annotation:1.0.0")
      implementation(project(":module07:module496:module4"))
        }
      }
      androidInstrumentedTest {
        dependencies {
      implementation("androidx.annotation:annotation:1.0.0")
        }
      }
      androidUnitTest {
        dependencies {
        }
      }
    }
  }
}
