plugins {
  id 'org.jetbrains.kotlin.multiplatform'
  id 'com.android.kotlin.multiplatform.library'
}

kotlin {
  androidLibrary {
    namespace = "com.android.example.module_4f1a776a"
    compileSdk = 31
    minSdk = 24

      withAndroidTestOnDeviceBuilder {
        it.compilationName = "instrumentedTest"
        it.defaultSourceSetName = "androidInstrumentedTest"
        it.sourceSetTreeName = "test"
      }

      withAndroidTestOnJvmBuilder {
        it.defaultSourceSetName = "androidUnitTest"
      }

      sourceSets {
        androidMain {
          dependencies {
      annotationProcessor("com.google.dagger:dagger-compiler:2.43.1")
      api(project(":module03:module25:module3"))
      api(project(":module03:module25:module6"))
      api(project(":module15:module1:module1"))
      api(project(":module23:module5:module23"))
      api(project(":module23:module5:module29:module1"))
      api("com.google.dagger:dagger:2.43.1")
      compileOnly(project(":module07:module505:module1"))
      compileOnly(project(":module07:module585:module1"))
      compileOnly("androidx.annotation:annotation:1.0.0")
      compileOnly("androidx.compose.runtime:runtime:1.2.0-alpha07")
      compileOnly("com.squareup.anvil:annotations:2.4.1")
      compileOnly("org.jetbrains.kotlin:kotlin-parcelize-runtime:1.7.20")
        }
      }
      androidInstrumentedTest {
        dependencies {
      implementation(project(":module07:module505:module1"))
      implementation(project(":module07:module585:module1"))
      implementation("androidx.annotation:annotation:1.0.0")
      implementation("androidx.compose.runtime:runtime:1.2.0-alpha07")
      implementation("com.squareup.anvil:annotations:2.4.1")
      implementation("org.jetbrains.kotlin:kotlin-parcelize-runtime:1.7.20")
        }
      }
      androidUnitTest {
        dependencies {
        }
      }
    }
  }
}
