plugins {
  id 'org.jetbrains.kotlin.multiplatform'
  id 'com.android.kotlin.multiplatform.library'
}

kotlin {
  androidLibrary {
    namespace = "com.android.example.module_91ed0702"
    compileSdk = 31
    minSdk = 24

      withAndroidTestOnDeviceBuilder {
        it.compilationName = "instrumentedTest"
        it.defaultSourceSetName = "androidInstrumentedTest"
        it.sourceSetTreeName = "test"
      }

      withAndroidTestOnJvmBuilder {
        it.defaultSourceSetName = "androidUnitTest"
      }

      sourceSets {
        androidMain {
          dependencies {
      api(project(":module06:module07:module4"))
      api(project(":module06:module16:module04"))
      api(project(":module06:module16:module06"))
      api(project(":module06:module16:module12"))
      api(project(":module06:module16:module13"))
      api(project(":module07:module194:module1"))
      api(project(":module07:module286:module3"))
      api(project(":module07:module288:module4"))
      api(project(":module07:module532:module5"))
      api(project(":module08:module40:module6"))
      api("com.google.dagger:dagger:2.43.1")
      compileOnly("androidx.annotation:annotation:1.0.0")
      implementation("org.jetbrains.kotlin:kotlin-bom:1.7.20")
        }
      }
      androidInstrumentedTest {
        dependencies {
      implementation("androidx.annotation:annotation:1.0.0")
        }
      }
      androidUnitTest {
        dependencies {
        }
      }
    }
  }
}
