plugins {
  id 'org.jetbrains.kotlin.multiplatform'
  id 'com.android.kotlin.multiplatform.library'
}

kotlin {
  androidLibrary {
    namespace = "com.android.example.module_f1872a9b"
    compileSdk = 31
    minSdk = 24

      withAndroidTestOnDeviceBuilder {
        it.compilationName = "instrumentedTest"
        it.defaultSourceSetName = "androidInstrumentedTest"
        it.sourceSetTreeName = "test"
      }

      withAndroidTestOnJvmBuilder {
        it.defaultSourceSetName = "androidUnitTest"
      }

      sourceSets {
        androidMain {
          dependencies {
      api(project(":module01:module08:module3"))
      api(project(":module07:module156"))
      api(project(":module07:module194:module1"))
      api(project(":module07:module216:module05:module3:module1"))
      api(project(":module07:module401:module3"))
      api(project(":module07:module540:module2"))
      api(project(":module08:module37:module05:module6"))
      api(project(":module08:module37:module07:module6"))
      api(project(":module08:module41:module3"))
      api(project(":module08:module44:module3"))
      api(project(":module19:module1:module02:module3"))
      api(project(":module19:module2:module09:module1"))
      api(project(":module19:module2:module09:module4"))
      api(project(":module19:module2:module33:module3"))
      api("com.google.dagger:dagger:2.43.1")
      compileOnly("androidx.annotation:annotation:1.0.0")
      implementation("org.jetbrains.kotlin:kotlin-bom:1.7.20")
        }
      }
      androidInstrumentedTest {
        dependencies {
      implementation("androidx.annotation:annotation:1.0.0")
        }
      }
      androidUnitTest {
        dependencies {
        }
      }
    }
  }
}
